# Generated by Django 3.0.8 on 2020-07-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeHistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyentry',
            old_name='anotation',
            new_name='annotation',
        ),
    ]
